import Head from "next/head";
import Header from "../components/common/Header";
import Navbar from "../components/common/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Michael Peters - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
    </>
  );
}
